spring:
  application:
    name: dragons

mugloar:
  base-url: https://dragonsofmugloar.com


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

game:
  target-score: 1000
  max-turns: 1000
  thread-pool-size: 4
  batch-size: 50